"""More real-Marker-bug regression tests, generated by "do many more tests" -
each one converts a real PDF through real Marker and checks docmd's output,
not hand-written markdown. See test_postprocess_integration.py for the
first one (page-spanning table). Honest negative results are included too,
not just wins - see test_merged_header_cells_survive_cleanly.
"""

from pathlib import Path

from docmd import convert_document
from docmd.config import ConvertConfig
from docmd.converters.marker_converter import MarkerConverter

FIXTURES = Path(__file__).parent / "fixtures"


def test_inconsistent_heading_levels_get_normalized_to_match():
    """running_header.pdf has 4 structurally identical section headings
    (same paragraph style). On the machine this was first written on (macOS,
    MPS), raw Marker assigned them *different* levels - Section 1 came back
    H3, Sections 2-4 came back H2 - a genuine model inconsistency, not a
    deliberately constructed skip.

    That specific raw output isn't portable, though: CI (Linux, CPU) ran the
    exact same PDF through the exact same pinned Marker version and got all
    four sections back as H2 from the start - a real platform-dependent
    difference in the underlying ML model's inference, not something our
    code controls. Hard-pinning the raw "bug" broke CI twice for that
    reason. So this only *asserts* the thing docmd actually guarantees -
    consistent heading levels across all four sections, however Marker
    happened to render them - and reports (without failing) whether this
    particular run's raw output shows the original inconsistency."""
    raw = MarkerConverter().convert(str(FIXTURES / "running_header.pdf"), ConvertConfig())
    if "### **Section 1: Findings**" in raw.markdown:
        print("raw Marker output reproduced the H3-vs-H2 inconsistency on this run")
    else:
        print("raw Marker output did not reproduce the inconsistency on this run/platform")

    result = convert_document(str(FIXTURES / "running_header.pdf"))
    levels = {
        n: "###" if f"### **Section {n}: Findings**" in result.markdown else "##"
        for n in range(1, 5)
    }
    assert len(set(levels.values())) == 1, f"inconsistent levels in docmd output: {levels}"


def test_running_header_does_not_leak_into_output():
    """The bold text drawn at a fixed position on every page ("CONFIDENTIAL
    - INTERNAL REPORT") never appears in Marker's raw markdown at all -
    Marker's own PageHeaderProcessor already strips repeated page headers.
    This is an honest negative result: docmd's duplicate-heading dedup
    wasn't needed here because Marker solved it upstream. Pinned as a
    regression test so a future Marker version silently changing this
    doesn't go unnoticed."""
    raw = MarkerConverter().convert(str(FIXTURES / "running_header.pdf"), ConvertConfig())
    assert "CONFIDENTIAL" not in raw.markdown


def test_merged_header_cells_survive_cleanly():
    """merged_cells.pdf has a spanned header cell (colspan). On the machine
    this was first written on, raw Marker already renders it as a clean,
    consistent 5-column table with no ragged rows - an honest negative
    result, nothing for table_cleanup.py to fix.

    Same lesson as test_inconsistent_heading_levels_get_normalized_to_match:
    the exact raw structure is backend inference output, not something
    docmd controls, so it's reported (via print) rather than asserted. What
    docmd actually guarantees - a well-formed, consistent table in the
    processed output, with the real data intact - is what's asserted."""
    raw = MarkerConverter().convert(str(FIXTURES / "merged_cells.pdf"), ConvertConfig())
    raw_table_lines = [l for l in raw.markdown.splitlines() if l.strip().startswith("|")]
    raw_col_counts = {line.count("|") for line in raw_table_lines}
    print(f"raw table: {len(raw_table_lines)} rows, column counts seen: {raw_col_counts}")

    result = convert_document(str(FIXTURES / "merged_cells.pdf"))
    proc_table_lines = [l for l in result.markdown.splitlines() if l.strip().startswith("|")]
    proc_col_counts = {line.count("|") for line in proc_table_lines}
    assert len(proc_col_counts) == 1, f"docmd output has inconsistent column counts: {proc_col_counts}"
    assert "West" in result.markdown and "$1.2M" in result.markdown


def test_alt_text_mode_actually_saves_the_image(tmp_path):
    """Regression test for a real bug found while doing this testing:
    `output_dir` was accepted by apply_image_handling() but never actually
    threaded through from convert()/convert_document(), so alt-text mode
    produced a markdown image link pointing to a file that was never
    written anywhere. Fixed in docmd/__init__.py and docmd/cli.py."""
    result = convert_document(
        str(FIXTURES / "with_image.pdf"),
        config=ConvertConfig(image_mode="alt-text"),
        output_dir=tmp_path,
    )
    assert "![Image 1](" in result.markdown

    saved_images = list(tmp_path.glob("*.jpeg"))
    assert len(saved_images) == 1
    assert saved_images[0].name in result.markdown
    # A real, valid JPEG - not an empty/placeholder file.
    assert saved_images[0].read_bytes()[:2] == b"\xff\xd8"


def test_placeholder_mode_never_writes_image_files(tmp_path):
    """The default mode should never touch the filesystem, even if an
    output_dir happens to be passed."""
    result = convert_document(
        str(FIXTURES / "with_image.pdf"),
        config=ConvertConfig(image_mode="placeholder"),
        output_dir=tmp_path,
    )
    assert "omitted" in result.markdown
    assert list(tmp_path.iterdir()) == []
